name: cross_desktop_remote
description: "Cross-platform remote desktop controller and host client."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  characters: ^1.4.1
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.6.0
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
